version: '3.9'

services:
  @apex:project_name:var:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  mariadb:
    image: mariadb:10.4.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root-secure-password"
      MYSQL_USER: "@apex:project_name:var_app"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "@apex:project_name:var"
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local
